trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'Your-Service-Connection-Name'  # Replace with your service connection name
  resourceGroupName: 'bicep-app'                  # Replace with your target resource group
  location: 'uksouth'
  environment: 'dev'
  appName: 'myapp'

stages:
  - stage: DeployInfra
    displayName: 'Deploy Bicep Infrastructure'
    jobs:
      - job: DeployBicep
        displayName: 'Run Bicep Deployment'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureCLI@2
            name: Deploy
            inputs:
              azureSubscription: 'Azure subscription 1(525c7c1f-f5e9-4bf4-8d7a-5b7a06889a12)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Starting deployment to $(resourceGroupName)..."
                az deployment group create \
                --resource-group $(resourceGroupName) \
                --template-file infrastructure/main.bicep \
                --parameters @infrastructure/parameters.$(environment).json \
                --parameters environment=$(environment) location=$(location) appName=$(appName)
                echo "Deployment complete."
